ALTER USER ACME_ADMIN
  SET 
      DISPLAY_NAME = 'ACME Car Dealer',
      DEFAULT_ROLE = 'SYSADMIN',
      DEFAULT_WAREHOUSE = 'ACME_WH';

USE ROLE ACCOUNTADMIN;
GRANT OWNERSHIP ON USER ACME_ADMIN TO ROLE SYSADMIN REVOKE CURRENT GRANTS;

USE ROLE SYSADMIN;
ALTER USER ACME_ADMIN
  SET DISPLAY_NAME = 'ACME Car Dealer';

SHOW GRANTS ON USER ACME_ADMIN;